// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uebung.Data;

#nullable disable

namespace Uebung.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511221928_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Uebung.Models.ListenObjekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjektId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjektId");

                    b.ToTable("ListenObjekte");
                });

            modelBuilder.Entity("Uebung.Models.Objekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Objekte");
                });

            modelBuilder.Entity("Uebung.Models.ListenObjekt", b =>
                {
                    b.HasOne("Uebung.Models.Objekt", null)
                        .WithMany("ListenObjekt")
                        .HasForeignKey("ObjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uebung.Models.Objekt", b =>
                {
                    b.Navigation("ListenObjekt");
                });
#pragma warning restore 612, 618
        }
    }
}
