// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _250217_Kundenliste.Data;

#nullable disable

namespace _250217_Kundenliste.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("_250217_Kundenliste.Models.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Erstellungsdatum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KundeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lagerbestand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("_250217_Kundenliste.Models.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Geburtsdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("_250217_Kundenliste.Models.Artikel", b =>
                {
                    b.HasOne("_250217_Kundenliste.Models.Kunde", null)
                        .WithMany("ArtikelListe")
                        .HasForeignKey("KundeId");
                });

            modelBuilder.Entity("_250217_Kundenliste.Models.Kunde", b =>
                {
                    b.Navigation("ArtikelListe");
                });
#pragma warning restore 612, 618
        }
    }
}
